- name: Standard Linux Playbooks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install apt modules
    yum:
      name:
      - git
      - postgresql
      - postgresql-server
      state: present
  - name: Create temporary directory
    file:
      path: /tmp/joe
      state: directory