- name: Standard Linux Playbooks
  hosts: all
  tasks:
  - name: Install yum modules
    yum:
      name:
      - httpd
      - git
      - nginx
      - postgresql
      - postgresql-server
      state: present
  - name: Create temporary directory
    file:
      path: /tmp/joe
      state: directory