- name: Remove Standard Linux Playbooks
  hosts: all
  tasks:
  - name: Uninstall apt modules
    apt:
      name:
      - git
      - nginx
      - postgresql
      - postgresql-server
      state: absent
  - name: Remove temporary directory
    file:
      path: /tmp/joe
      state: absent