- name: Windows Install Playbook
  hosts: all
  tasks:
  - name: Install chocolatey
    win_chocolatey:
      name:
      - chocolatey
      - chocolatey-core.extension
      state: present
  - name: Ensure 7-Zip is installed via Chocolatey
    win_chocolatey:
      name: 7zip
      state: present
  - name: Ensure 7-Zip is not installed via Chocolatey
    win_chocolatey:
      name: 7zip
      state: present
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: C:\Temp
      state: directory
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: C:\Temp\foo
      state: directory
