- name: Remove Standard Windows Playbook
  hosts: all
  tasks:
  - name: Ensure 7-Zip is uninstalled via Chocolatey
    win_chocolatey:
      name: 7zip
      state: absent
  - name: Touch a file
    win_file:
      path: C:\Temp
      state: absent
  - name: Touch a file
    win_file:
      path: C:\Temp\foo
      state: absent
