- name: Remove Standard Windows Playbook
  hosts: all
  tasks:
  - name: Ensure 7-Zip is uninstalled via Chocolatey
    win_chocolatey:
      name: 7zip
      state: absent
  - name: Ensure 7-Zip is not uninstalled via Chocolatey
    win_chocolatey:
      name: 7zip
      state: absent
